### ISSUE TITLE
Interface modifications

### ISSUE THREAD

**Issue by josiah-tesfu** [EdgePi-Cloud/node-red-edgepi-digital-out#16]
- On the EdgePi, the output has channel labels in the form OUT 1, while the node has the labels in the form D-OUT1. It might be clearer to have the labels match. This also applies to the input channel labels.
- Some fields have colons while others don't. They should all be consistent.
- Rpc Server --> RPC Server
- The placeholder text, "IP Address" under the RPC Server field should indicate an option for entering the hostname, e.g. "IP Address/ Hostname"
- Remove the word "node" from the node name. No other node-RED nodes have it and it's a bit redundant.

**Comment by farzadpanahi** [comment]
On the label it is `OUT x`  because that output can be either digital or analog based on configuration. 
But your concern is valid. I don't have a solution for that at the moment. Let me know if you can think of something.

**Comment by josiah-tesfu** [comment]
@farzadpanahi what if we changed "Channel" to "Digital Output", and then had "OUT 1, OUT 2..." for the options?

Alternatively, since the node is called digital-out, it may not be necessary to even specify 'digital' in the field options. We could also clarify that this node is for digital not analog output in the README or somewhere else in the node description.

**Comment by farzadpanahi** [comment]
can you send a screenshot of how that node's settings look like right now ?
